export var cultureInfoList=[
    { "code": "af", "language": "Afrikaans", "country": "" },
    { "code": "af-ZA", "language": "Afrikaans", "country": "South Africa" },
    { "code": "ar", "language": "Arabic", "country": "" },
    {
        "code": "ar-AE",
        "language": "Arabic",
        "country": "United Arab Emirates"
    },
    { "code": "ar-BH", "language": "Arabic", "country": "Bahrain" },
    { "code": "ar-DZ", "language": "Arabic", "country": "Algeria" },
    { "code": "ar-EG", "language": "Arabic", "country": "Egypt" },
    { "code": "ar-IQ", "language": "Arabic", "country": "Iraq" },
    { "code": "ar-JO", "language": "Arabic", "country": "Jordan" },
    { "code": "ar-KW", "language": "Arabic", "country": "Kuwait" },
    { "code": "ar-LB", "language": "Arabic", "country": "Lebanon" },
    { "code": "ar-LY", "language": "Arabic", "country": "Libya" },
    { "code": "ar-MA", "language": "Arabic", "country": "Morocco" },
    { "code": "ar-OM", "language": "Arabic", "country": "Oman" },
    { "code": "ar-QA", "language": "Arabic", "country": "Qatar" },
    { "code": "ar-SA", "language": "Arabic", "country": "Saudi Arabia" },
    { "code": "ar-SY", "language": "Arabic", "country": "Syria" },
    { "code": "ar-TN", "language": "Arabic", "country": "Tunisia" },
    { "code": "ar-YE", "language": "Arabic", "country": "Yemen" },
    { "code": "be", "language": "Belarusian", "country": "" },
    { "code": "be-BY", "language": "Belarusian", "country": "Belarus" },
    { "code": "bg", "language": "Bulgarian", "country": "" },
    { "code": "bg-BG", "language": "Bulgarian", "country": "Bulgaria" },
    { "code": "ca", "language": "Catalan", "country": "" },
    { "code": "ca-ES", "language": "Catalan", "country": "Catalan" },
    { "code": "cs", "language": "Czech", "country": "" },
    { "code": "cs-CZ", "language": "Czech", "country": "Czech Republic" },
    { "code": "Cy-az", "language": "Azeri (Cyrillic)", "country": "" },
    {
        "code": "Cy-az-AZ",
        "language": "Azeri (Cyrillic)",
        "country": "Azerbaijan"
    },
    { "code": "Cy-sr", "language": "Serbian (Cyrillic)", "country": "" },
    {
        "code": "Cy-sr-SP",
        "language": "Serbian (Cyrillic)",
        "country": "Serbia"
    },
    { "code": "Cy-uz", "language": "Uzbek (Cyrillic)", "country": "" },
    {
        "code": "Cy-uz-UZ",
        "language": "Uzbek (Cyrillic)",
        "country": "Uzbekistan"
    },
    { "code": "da", "language": "Danish", "country": "" },
    { "code": "da-DK", "language": "Danish", "country": "Denmark" },
    { "code": "de", "language": "German", "country": "" },
    { "code": "de-AT", "language": "German", "country": "Austria" },
    { "code": "de-CH", "language": "German", "country": "Switzerland" },
    { "code": "de-DE", "language": "German", "country": "Germany" },
    { "code": "de-LI", "language": "German", "country": "Liechtenstein" },
    { "code": "de-LU", "language": "German", "country": "Luxembourg" },
    { "code": "div", "language": "Dhivehi", "country": "" },
    { "code": "div-MV", "language": "Dhivehi", "country": "Maldives" },
    { "code": "el", "language": "Greek", "country": "" },
    { "code": "el-GR", "language": "Greek", "country": "Greece" },
    { "code": "en", "language": "English", "country": "" },
    { "code": "en-AU", "language": "English", "country": "Australia" },
    { "code": "en-BZ", "language": "English", "country": "Belize" },
    { "code": "en-CA", "language": "English", "country": "Canada" },
    { "code": "en-CB", "language": "English", "country": "Caribbean" },
    { "code": "en-GB", "language": "English", "country": "United Kingdom" },
    { "code": "en-IE", "language": "English", "country": "Ireland" },
    { "code": "en-JM", "language": "English", "country": "Jamaica" },
    { "code": "en-NZ", "language": "English", "country": "New Zealand" },
    { "code": "en-PH", "language": "English", "country": "Philippines" },
    {
        "code": "en-TT",
        "language": "English",
        "country": "Trinidad and Tobago"
    },
    { "code": "en-US", "language": "English", "country": "United States" },
    { "code": "en-ZA", "language": "English", "country": "South Africa" },
    { "code": "en-ZW", "language": "English", "country": "Zimbabwe" },
    { "code": "es", "language": "Spanish", "country": "" },
    { "code": "es-AR", "language": "Spanish", "country": "Argentina" },
    { "code": "es-BO", "language": "Spanish", "country": "Bolivia" },
    { "code": "es-CL", "language": "Spanish", "country": "Chile" },
    { "code": "es-CO", "language": "Spanish", "country": "Colombia" },
    { "code": "es-CR", "language": "Spanish", "country": "Costa Rica" },
    { "code": "es-DO", "language": "Spanish", "country": "Dominican Republic" },
    { "code": "es-EC", "language": "Spanish", "country": "Ecuador" },
    { "code": "es-ES", "language": "Spanish", "country": "Spain" },
    { "code": "es-GT", "language": "Spanish", "country": "Guatemala" },
    { "code": "es-HN", "language": "Spanish", "country": "Honduras" },
    { "code": "es-MX", "language": "Spanish", "country": "Mexico" },
    { "code": "es-NI", "language": "Spanish", "country": "Nicaragua" },
    { "code": "es-PA", "language": "Spanish", "country": "Panama" },
    { "code": "es-PE", "language": "Spanish", "country": "Peru" },
    { "code": "es-PR", "language": "Spanish", "country": "Puerto Rico" },
    { "code": "es-PY", "language": "Spanish", "country": "Paraguay" },
    { "code": "es-SV", "language": "Spanish", "country": "El Salvador" },
    { "code": "es-UY", "language": "Spanish", "country": "Uruguay" },
    { "code": "es-VE", "language": "Spanish", "country": "Venezuela" },
    { "code": "et", "language": "Estonian", "country": "" },
    { "code": "et-EE", "language": "Estonian", "country": "Estonia" },
    { "code": "eu", "language": "Basque", "country": "" },
    { "code": "eu-ES", "language": "Basque", "country": "Basque" },
    { "code": "fa", "language": "Farsi", "country": "" },
    { "code": "fa-IR", "language": "Farsi", "country": "Iran" },
    { "code": "fi", "language": "Finnish", "country": "" },
    { "code": "fi-FI", "language": "Finnish", "country": "Finland" },
    { "code": "fo", "language": "Faroese", "country": "" },
    { "code": "fo-FO", "language": "Faroese", "country": "Faroe Islands" },
    { "code": "fr", "language": "French", "country": "" },
    { "code": "fr-BE", "language": "French", "country": "Belgium" },
    { "code": "fr-CA", "language": "French", "country": "Canada" },
    { "code": "fr-CH", "language": "French", "country": "Switzerland" },
    { "code": "fr-FR", "language": "French", "country": "France" },
    { "code": "fr-LU", "language": "French", "country": "Luxembourg" },
    { "code": "fr-MC", "language": "French", "country": "Monaco" },
    { "code": "gl", "language": "Galician", "country": "" },
    { "code": "gl-ES", "language": "Galician", "country": "Galician" },
    { "code": "gu", "language": "Gujarati", "country": "" },
    { "code": "gu-IN", "language": "Gujarati", "country": "India" },
    { "code": "he", "language": "Hebrew", "country": "" },
    { "code": "he-IL", "language": "Hebrew", "country": "Israel" },
    { "code": "hi", "language": "Hindi", "country": "" },
    { "code": "hi-IN", "language": "Hindi", "country": "India" },
    { "code": "hr", "language": "Croatian", "country": "" },
    { "code": "hr-HR", "language": "Croatian", "country": "Croatia" },
    { "code": "hu", "language": "Hungarian", "country": "" },
    { "code": "hu-HU", "language": "Hungarian", "country": "Hungary" },
    { "code": "hy", "language": "Armenian", "country": "" },
    { "code": "hy-AM", "language": "Armenian", "country": "Armenia" },
    { "code": "id", "language": "Indonesian", "country": "" },
    { "code": "id-ID", "language": "Indonesian", "country": "Indonesia" },
    { "code": "is", "language": "Icelandic", "country": "" },
    { "code": "is-IS", "language": "Icelandic", "country": "Iceland" },
    { "code": "it", "language": "Italian", "country": "" },
    { "code": "it-CH", "language": "Italian", "country": "Switzerland" },
    { "code": "it-IT", "language": "Italian", "country": "Italy" },
    { "code": "ja", "language": "Japanese", "country": "" },
    { "code": "ja-JP", "language": "Japanese", "country": "Japan" },
    { "code": "ka", "language": "Georgian", "country": "" },
    { "code": "ka-GE", "language": "Georgian", "country": "Georgia" },
    { "code": "kk", "language": "Kazakh", "country": "" },
    { "code": "kk-KZ", "language": "Kazakh", "country": "Kazakhstan" },
    { "code": "kn", "language": "Kannada", "country": "" },
    { "code": "kn-IN", "language": "Kannada", "country": "India" },
    { "code": "ko", "language": "Korean", "country": "" },
    { "code": "kok", "language": "Konkani", "country": "" },
    { "code": "kok-IN", "language": "Konkani", "country": "India" },
    { "code": "ko-KR", "language": "Korean", "country": "Korea" },
    { "code": "ky", "language": "Kyrgyz", "country": "" },
    { "code": "ky-KZ", "language": "Kyrgyz", "country": "Kazakhstan" },
    { "code": "lt", "language": "Lithuanian", "country": "" },
    { "code": "Lt-az", "language": "Azeri (Latin)", "country": "" },
    {
        "code": "Lt-az-AZ",
        "language": "Azeri (Latin)",
        "country": "Azerbaijan"
    },
    { "code": "lt-LT", "language": "Lithuanian", "country": "Lithuania" },
    { "code": "Lt-sr", "language": "Serbian (Latin)", "country": "" },
    { "code": "Lt-sr-SP", "language": "Serbian (Latin)", "country": "Serbia" },
    { "code": "Lt-uz", "language": "Uzbek (Latin)", "country": "" },
    {
        "code": "Lt-uz-UZ",
        "language": "Uzbek (Latin)",
        "country": "Uzbekistan"
    },
    { "code": "lv", "language": "Latvian", "country": "" },
    { "code": "lv-LV", "language": "Latvian", "country": "Latvia" },
    { "code": "mk", "language": "Macedonian (FYROM)", "country": "" },
    { "code": "mk-MK", "language": "Macedonian (FYROM)", "country": "" },
    { "code": "mn", "language": "Mongolian", "country": "" },
    { "code": "mn-MN", "language": "Mongolian", "country": "Mongolia" },
    { "code": "mr", "language": "Marathi", "country": "" },
    { "code": "mr-IN", "language": "Marathi", "country": "India" },
    { "code": "ms", "language": "Malay", "country": "" },
    { "code": "ms-BN", "language": "Malay", "country": "Brunei" },
    { "code": "ms-MY", "language": "Malay", "country": "Malaysia" },
    { "code": "nb", "language": "Norwegian (Bokm??l)", "country": "" },
    { "code": "nb-NO", "language": "Norwegian (Bokm??l)", "country": "Norway" },
    { "code": "nl", "language": "Dutch", "country": "" },
    { "code": "nl-BE", "language": "Dutch", "country": "Belgium" },
    { "code": "nl-NL", "language": "Dutch", "country": "The Netherlands" },
    { "code": "nn", "language": "Norwegian (Nynorsk)", "country": "" },
    { "code": "nn-NO", "language": "Norwegian (Nynorsk)", "country": "Norway" },
    { "code": "pa", "language": "Punjabi", "country": "" },
    { "code": "pa-IN", "language": "Punjabi", "country": "India" },
    { "code": "pl", "language": "Polish", "country": "" },
    { "code": "pl-PL", "language": "Polish", "country": "Poland" },
    { "code": "pt", "language": "Portuguese", "country": "" },
    { "code": "pt-BR", "language": "Portuguese", "country": "Brazil" },
    { "code": "pt-PT", "language": "Portuguese", "country": "Portugal" },
    { "code": "ro", "language": "Romanian", "country": "" },
    { "code": "ro-RO", "language": "Romanian", "country": "Romania" },
    { "code": "ru", "language": "Russian", "country": "" },
    { "code": "ru-RU", "language": "Russian", "country": "Russia" },
    { "code": "sa", "language": "Sanskrit", "country": "" },
    { "code": "sa-IN", "language": "Sanskrit", "country": "India" },
    { "code": "sk", "language": "Slovak", "country": "" },
    { "code": "sk-SK", "language": "Slovak", "country": "Slovakia" },
    { "code": "sl", "language": "Slovenian", "country": "" },
    { "code": "sl-SI", "language": "Slovenian", "country": "Slovenia" },
    { "code": "sq", "language": "Albanian", "country": "" },
    { "code": "sq-AL", "language": "Albanian", "country": "Albania" },
    { "code": "sv", "language": "Swedish", "country": "" },
    { "code": "sv-FI", "language": "Swedish", "country": "Finland" },
    { "code": "sv-SE", "language": "Swedish", "country": "Sweden" },
    { "code": "sw", "language": "Swahili", "country": "" },
    { "code": "sw-KE", "language": "Swahili", "country": "Kenya" },
    { "code": "syr", "language": "Syriac", "country": "" },
    { "code": "syr-SY", "language": "Syriac", "country": "Syria" },
    { "code": "ta", "language": "Tamil", "country": "" },
    { "code": "ta-IN", "language": "Tamil", "country": "India" },
    { "code": "te", "language": "Telugu", "country": "" },
    { "code": "te-IN", "language": "Telugu", "country": "India" },
    { "code": "th", "language": "Thai", "country": "" },
    { "code": "th-TH", "language": "Thai", "country": "Thailand" },
    { "code": "tr", "language": "Turkish", "country": "" },
    { "code": "tr-TR", "language": "Turkish", "country": "Turkey" },
    { "code": "tt", "language": "Tatar", "country": "" },
    { "code": "tt-RU", "language": "Tatar", "country": "Russia" },
    { "code": "uk", "language": "Ukrainian", "country": "" },
    { "code": "uk-UA", "language": "Ukrainian", "country": "Ukraine" },
    { "code": "ur", "language": "Urdu", "country": "" },
    { "code": "ur-PK", "language": "Urdu", "country": "Pakistan" },
    { "code": "vi", "language": "Vietnamese", "country": "" },
    { "code": "vi-VN", "language": "Vietnamese", "country": "Vietnam" },
    { "code": "zh", "language": "Chinese", "country": "" },
    { "code": "zh-CHS", "language": "Chinese (Simplified)", "country": "" },
    { "code": "zh-CHT", "language": "Chinese (Traditional)", "country": "" },
    { "code": "zh-CN", "language": "Chinese", "country": "China" },
    { "code": "zh-HK", "language": "Chinese", "country": "Hong Kong SAR" },
    { "code": "zh-MO", "language": "Chinese", "country": "Macau SAR" },
    { "code": "zh-SG", "language": "Chinese", "country": "Singapore" },
    { "code": "zh-TW", "language": "Chinese", "country": "Taiwan" }
]
